# Site settings
title: Private Ryan's Portfolio
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "portfolio.privateryan.me" # the base hostname & protocol for your site

twitter_username:
github_username: privateryann1

# Build settings
markdown: kramdown
